"""Assembly: what wraps what, and what every failure looks like on the way out.

The order in here is the contract. A shipped client parses `{"error":{"message":…}}`
and nothing else, so every layer that can refuse a request — the rate limiter, the body
ceiling, the validator, the router's own 404 — has to produce that same envelope, and a
body FastAPI cannot decode has to be a 400 rather than the 422 it would rather send.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from starlette.exceptions import HTTPException
from starlette.responses import Response
from starlette.staticfiles import StaticFiles
from starlette.types import ASGIApp, Receive, Scope, Send

from deylee_api.config import Config
from deylee_api.db import UNAVAILABLE_MESSAGE, Store, StoreTimedOut
from deylee_api.errors import APIError, error_response
from deylee_api.mail import Mailer
from deylee_api.ratelimit import BodyLimitMiddleware, RateLimiter, RateLimitMiddleware
from deylee_api.routes import auth, contact, feedback, sync, witness
from deylee_api.tokens import TokenService

# See BodyLimitMiddleware: a conforming push of 500 changes with 2000-character notes is
# about 4.2 MB, so anything under that stalls sync permanently rather than rejecting one
# request. Pinned here so the number moves when somebody decides it should.
MAX_BODY_BYTES = 8 * 1024 * 1024


class UnhandledErrorMiddleware:
    """Logs the errors nobody chose to return, and answers them in the envelope.

    An `APIError` is a deliberate answer — 401 for a bad token, 409 for a stale cursor —
    and never reaches here: its handler sits further in. Logging those at error level
    would bury the real faults in noise generated by ordinary clients. Anything that does
    reach here is a bug, and a 500 with no log line behind it is the hardest kind to
    chase: the client sees a blank failure and the server has nothing to say about it.

    A middleware rather than an `Exception` handler, because Starlette's
    `ServerErrorMiddleware` re-raises after calling one, which turns every 500 into a
    traceback the test client raises instead of a response it can assert on.
    """

    def __init__(self, app: ASGIApp, *, logger: logging.Logger) -> None:
        self.app = app
        self.logger = logger

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        try:
            await self.app(scope, receive, send)
        except Exception as error:
            self.logger.error(
                "unhandled error method=%s path=%s error=%s: %s",
                scope.get("method", ""),
                scope.get("path", ""),
                type(error).__name__,
                error,
                exc_info=error,
            )
            # The same generic sentence the auth routes use for their own 500s: it
            # tells the caller to retry and tells an attacker nothing.
            await error_response(500, "The request could not be completed.")(scope, receive, send)


class _CachedStatic(StaticFiles):
    """Starlette's static server with the update feed's cache window on every file.

    `StaticFiles` rather than a handler of our own: it is the piece that has already
    thought about a request path containing `../`, and a static file server is exactly
    the kind of thing that looks trivial until it serves `/etc/passwd`.
    """

    async def get_response(self, path: str, scope: Scope) -> Response:
        response = await super().get_response(path, scope)
        response.headers.setdefault("Cache-Control", "max-age=300")
        return response


def _validation_message(error: RequestValidationError) -> str:
    """The sentence for a body the route could not decode.

    These mirror Hummingbird's JSON decoder word for word, because they are what the
    shipped Mac app has been surfacing to users all along — it prints whatever the
    envelope carries.
    """
    first = next(iter(error.errors()), None)
    if first is None:
        return "Unexpected error"
    if first["type"] == "json_invalid":
        return "The given data was not valid JSON."
    # loc[0] is the source ("body", "query"); the rest is the path within it.
    path = ".".join(str(part) for part in first["loc"][1:]) or "body"
    if first["type"] == "missing":
        return f"Coding key `{path}` not found."
    return f"Type mismatch for `{path}` key."


def create_app(
    *,
    config: Config,
    store: Store,
    tokens: TokenService,
    mailer: Mailer,
    limiter: RateLimiter,
    logger: logging.Logger,
    assert_rls: bool = True,
) -> FastAPI:
    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        await store.start()
        # After the pool is up and before a single request is served. Tenancy rests on
        # the row-level-security policies binding, and they bind only to an ordinary
        # role — so a process connected as a superuser is one that would serve every
        # customer's hours to whoever asked, while looking entirely healthy.
        if assert_rls:
            await store.assert_not_bypassing_row_level_security()
        yield
        await store.close()

    # No /docs, /redoc or /openapi.json: the Swift server had no such routes, and the
    # public surface is the one in docs/SYNC_PROTOCOL.md.
    app = FastAPI(lifespan=lifespan, docs_url=None, redoc_url=None, openapi_url=None)

    # Handlers read these off `request.app.state`; no DI framework, no globals.
    app.state.config = config
    app.state.store = store
    app.state.tokens = tokens
    app.state.mailer = mailer
    app.state.limiter = limiter
    app.state.logger = logger

    async def on_api_error(request: Request, error: APIError) -> Response:
        return error_response(error.status, error.message, error.headers)

    async def on_validation_error(request: Request, error: RequestValidationError) -> Response:
        # 400, never FastAPI's 422: the Swift routes answered 400 for a body they could
        # not decode and a shipped client depends on it.
        return error_response(400, _validation_message(error))

    async def on_store_timeout(request: Request, error: StoreTimedOut) -> Response:
        # Deliberate, so it is answered rather than logged as a bug — but a real fault,
        # so it is said out loud at warning level. The auth routes map this themselves;
        # this covers everything else, sync included.
        logger.warning(
            "database deadline exceeded method=%s path=%s", request.method, request.url.path
        )
        return error_response(503, UNAVAILABLE_MESSAGE)

    async def on_http_exception(request: Request, error: HTTPException) -> Response:
        # The router's own refusals — 404 for an unknown path, 405 for a wrong method —
        # so that even those arrive in the envelope.
        return error_response(error.status_code, str(error.detail), error.headers)

    app.add_exception_handler(APIError, on_api_error)
    app.add_exception_handler(RequestValidationError, on_validation_error)
    app.add_exception_handler(StoreTimedOut, on_store_timeout)
    app.add_exception_handler(HTTPException, on_http_exception)

    # Each `add_middleware` pushes to the front, so the last added runs first: the
    # catch-all wraps everything, then the rate limiter, then the body ceiling.
    app.add_middleware(BodyLimitMiddleware, max_bytes=MAX_BODY_BYTES, logger=logger)
    # Before anything expensive. Every password attempt costs a quarter-second of
    # database CPU by design, so an unauthenticated caller turns one cheap request into
    # real money; closing the timing channel made an unknown address cost the same as a
    # real one, which is why this lands with it rather than after it.
    app.add_middleware(RateLimitMiddleware, limiter=limiter, limit=600, window=60.0, logger=logger)
    app.add_middleware(UnhandledErrorMiddleware, logger=logger)
    # Outermost, so a preflight is answered before the rate limiter counts it — an OPTIONS
    # the browser sends on its own is not the caller spending anything.
    #
    # Credentials are off and the origin list is explicit. Together those mean this grants
    # the marketing site the ability to post its contact form and grants nobody the
    # ability to ride a session: no cookie is attached, and every other route reads its
    # identity from an Authorization header the browser will not add by itself.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=sorted(config.web_origins),
        allow_methods=["POST", "OPTIONS"],
        allow_headers=["content-type"],
        allow_credentials=False,
        max_age=600,
    )

    @app.get("/health")
    async def health() -> dict[str, str]:
        """Liveness only.

        Deliberately does not touch the database: a health check that fails when Postgres
        is briefly unreachable invites an orchestrator to kill a process that would
        otherwise have recovered on its own.
        """
        return {"status": "ok"}

    # The Mac app's update feed, when a directory is configured to serve it from.
    #
    # Public and unauthenticated on purpose: Sparkle fetches the appcast and the archive
    # with no credentials, which is also why this cannot live behind a private
    # repository. Authenticity does not come from the transport — every archive carries
    # an EdDSA signature the app checks against a public key compiled into it, so a
    # tampered file served from here is refused by the client rather than trusted
    # because it arrived over HTTPS.
    if config.updates_directory:
        app.mount("/updates", _CachedStatic(directory=config.updates_directory), name="updates")
        logger.info("serving updates directory=%s", config.updates_directory)

    for module in (auth, sync, witness, feedback, contact):
        app.include_router(module.router)

    return app
