import Hummingbird
import Logging

/// Logs the errors nobody chose to return.
///
/// An `HTTPError` is a deliberate answer — 401 for a bad token, 409 for a stale
/// cursor — and logging those at error level would bury the real faults in noise
/// generated by ordinary clients. Anything else reaching here is a bug, and a 500
/// with no log line behind it is the hardest kind to chase: the client sees a
/// blank failure and the server has nothing to say about it.
struct ErrorLogging<Context: RequestContext>: RouterMiddleware {
    let logger: Logger

    func handle(
        _ request: Request,
        context: Context,
        next: (Request, Context) async throws -> Response
    ) async throws -> Response {
        do {
            return try await next(request, context)
        } catch let error as HTTPError {
            throw error
        } catch StoreError.timedOut {
            // Deliberate, so it is answered rather than logged as a bug — but a real
            // fault, so it is said out loud at warning level. The auth routes map
            // this themselves; this covers everything else, sync included.
            logger.warning("database deadline exceeded", metadata: [
                "method": .string(request.method.rawValue),
                "path": .string(request.uri.path),
            ])
            throw HTTPError(.serviceUnavailable, message: StoreError.unavailableMessage)
        } catch {
            logger.error("unhandled error", metadata: [
                "method": .string(request.method.rawValue),
                "path": .string(request.uri.path),
                // `reflecting:` rather than `describing:`, because the useful part of
                // a PSQLError — the SQLSTATE and the server's message — lives in the
                // detailed form and is absent from the short one.
                "error": .string(String(reflecting: error)),
            ])
            throw error
        }
    }
}
